### ISSUE TITLE
Page permissions

### ISSUE THREAD

**Issue by chandso** [localwiki/localwiki#743]
Would it be possible to add "Only Registered Users" to the existing "Everyone" and "Only these users" security options currently available? I think this could provide a moderate level of protection for important pages, in particular the main page. Thanks!

**Comment by cgorringe** [comment]
I'd like to have a setting for the entire region/city's pages which would only permit edits from users who are logged in.  Let the admin for the region/city toggle this setting on/off.  I'd like the page histories to show who edits the pages, and also it helps prevent people from editing pages while logged out on accident.

**Comment by philipn** [comment]
I don't like this idea because this would not provide any additional "protection" over the usual security restrictions.  Right now, when you protect a page you set it to *only* be editable by a set of users.  Otherwise, it is editable by anyone that is allowed to edit.  This would complicate this security flow, and for no particular reason (security and protection-wise).  I'm closing this because restricting, on a per-page basis, editing to authenticated-only users isn't something I think we should do right now.

See https://github.com/localwiki/localwiki/issues/747 for an idea here.

**Comment by chandso** [comment]
No problem, Philip. Thanks for looking at it.
