### ISSUE TITLE
Pages view differently depending on whether you are logged in or not.

### ISSUE THREAD

**Issue by jrpstonecarver** [localwiki/localwiki#777]
I am attaching 2 files.  Chrome_logged_into_localwiki.png is a screen capture of a Google Chrome instance running on Linux. In this case I am logged into localwiki and viewing a particular page.  A couple of days before I had edited that page, and I can see my edit in this window.

The other files is firefox_not_logged_into_localwiki.png, which is a screen capture from the same computer, at the same time, of a firefox window where I view the very same page in localwiki but without being logged into it. In this case the edit I made a couple of days ago is not visible at all.

The edit in question is the addition of the Soquel Demonstration Forest Station to the list of weather stations in the area. It only shows up in the Chrome window, but not in the FF window.

I was informed about this because I edited the page and sent out a note saying I had added it to the page to our local email list. Another user got back to me saying "really? I don't see it." So I went and looked on my phone browser, and it wasn't there. Then I came home and checked on the big computer and it _is_ still there, but only if you view the page logged into localwiki. If you are not logged in, you cannot see the edit.

That is clearly a bug and needs fixing. I have encountered similar (probably related) issues in the past when I was editing a page without being logged in and could not see the edits myself in some cases, but this is the first time I have ever had it happen that some other user can't see something I added to a page due to the logged in / not logged in discrepancy.

The page in question is: https://localwiki.org/95033/Weather_Information

And the edit I made was done on Oct 16 at 10:58.  However I now see that an anonymous user edited the page after I did. Maybe that is the actual heart of the problem somehow?

This is bad and needs fixing regardless. The pages should always display current - most recent - content regardless of the logged in status of the user or the editing history.

Thank you!

--jeffp

![chrome_logged_into_localwiki](https://cloud.githubusercontent.com/assets/17531825/19546333/b85787f6-9643-11e6-8dff-d289a75d1be8.png)
![firefox_not_logged_into_localwiki](https://cloud.githubusercontent.com/assets/17531825/19546334/b858fb0e-9643-11e6-843a-e7bd4d54d4b1.png)

**Comment by philipn** [comment]
This has been fixed on the page(s) in question.  I've moved the next steps over here: https://github.com/localwiki/localwiki-backend-server/issues/87 I'm closing this issue as this particular instance of the problem has been fixed, and https://github.com/localwiki/localwiki-backend-server/issues/87 will track the underlying issue here.

Technical notes:

This looks like a caching issue, similar (if not identical) to #746, #769. With #769, this was caused (or perhaps simply fixed) by a lack of a restart of the celery service, which does the cache invalidation after page save. 

Editing the page in question did not result in a cache refresh, as per report above.  Restarting the celery service (`service celery restart`) followed by editing the page resulted in a cache refresh.  My current hypothesis is that a `fab deploy` was done and the celery service wasn't restarted at some point.

Looking at the celery log at `/var/log/celery` doesn't show anything illuminating about cache invalidation.
